import type { EventItem } from "@/lib/types";

// Interessante internationale congressen rond low-carb en metabole
// gezondheid. Data en links gecontroleerd op de officiële websites.

export const MOCK_EVENTS: EventItem[] = [
  {
    slug: "smh-low-carb-san-diego-2026",
    titel: "Symposium for Metabolic Health – Low Carb San Diego",
    datum: "2026-08-13",
    einddatum: "2026-08-16",
    begintijd: "",
    eindtijd: "",
    locatie: "San Diego, VS",
    modaliteit: "hybride",
    organisator: "LowCarbUSA / Society of Metabolic Health Practitioners",
    beschrijving:
      "Sterk medisch-wetenschappelijk congres over therapeutische koolhydraatbeperking, insulineresistentie, hyperinsulinemie en inflammatie. Ook te volgen via livestream, met CME-accreditatie voor zorgprofessionals.",
    doelgroep: "Artsen, onderzoekers en andere zorgprofessionals",
    inschrijflink: "https://www.lowcarbusa.org/san-diego-2026/",
    prijs: "Zie website (livestream ook mogelijk)",
    afbeelding_url: "",
  },
  {
    slug: "low-carb-for-better-health-2026",
    titel: "Low Carb for Better Health",
    datum: "2026-09-26",
    einddatum: "2026-09-27",
    begintijd: "",
    eindtijd: "",
    locatie: "Burns, Tennessee, VS",
    modaliteit: "fysiek",
    organisator: "Low Carb for Better Health (LC4BH)",
    beschrijving:
      "Kleinschaliger congres voor professionals én geïnteresseerden, met een mix van wetenschap, praktijk en community, in een rustige retreat-achtige omgeving.",
    doelgroep: "Professionals en geïnteresseerden",
    inschrijflink: "https://www.lc4bh.com/",
    prijs: "Zie website",
    afbeelding_url: "",
  },
  {
    slug: "keto-pa-lou-za-2026",
    titel: "Keto Pa-LOU-za",
    datum: "2026-10-08",
    einddatum: "2026-10-10",
    begintijd: "",
    eindtijd: "",
    locatie: "Louisville, VS",
    modaliteit: "fysiek",
    organisator: "Watch Autumn Keto",
    beschrijving:
      "Meer publieksgericht evenement rond keto, low carb, ketovore en carnivore — bekend als de \"keto family reunion\", met sprekers, vendors en een sterke community-sfeer.",
    doelgroep: "Geïnteresseerden in keto, low carb, ketovore en carnivore",
    inschrijflink: "https://www.ketopalouza.com/",
    prijs: "Zie website",
    afbeelding_url: "",
  },
  {
    slug: "low-carb-sydney-2026",
    titel: "Low Carb Sydney 2026",
    datum: "2026-10-16",
    einddatum: "2026-10-18",
    begintijd: "",
    eindtijd: "",
    locatie: "Sydney, Australië",
    modaliteit: "fysiek",
    organisator: "Low Carb Down Under",
    beschrijving:
      "Groot internationaal congres van Low Carb Down Under, met lezingen en discussies over koolhydraatbeperking door internationale sprekers.",
    doelgroep: "Professionals en geïnteresseerden",
    inschrijflink: "https://lowcarbdownunder.com.au/events/",
    prijs: "Zie website",
    afbeelding_url: "",
  },
  {
    slug: "san-antonio-symposium-metabolic-health-2027",
    titel: "San Antonio Symposium for Metabolic Health",
    datum: "2027-01-29",
    einddatum: "2027-01-31",
    begintijd: "",
    eindtijd: "",
    locatie: "San Antonio, VS",
    modaliteit: "hybride",
    organisator: "LowCarbUSA",
    beschrijving:
      "Geaccrediteerd medisch congres over diabetes, obesitas, en cardiovasculaire en neurologische aandoeningen in relatie tot metabole gezondheid. Ook te volgen via livestream.",
    doelgroep: "Artsen, onderzoekers en andere zorgprofessionals",
    inschrijflink: "https://www.lowcarbusa.org/san-antonio-2027/",
    prijs: "Zie website (livestream ook mogelijk)",
    afbeelding_url: "",
  },
  {
    slug: "low-carb-cruise-2027",
    titel: "Low Carb Cruise",
    datum: "2027-06-11",
    einddatum: "2027-06-18",
    begintijd: "",
    eindtijd: "",
    locatie: "Vanaf Long Beach, VS",
    modaliteit: "fysiek",
    organisator: "Low Carb Cruise",
    beschrijving:
      "\"Seminar at sea\": een low-carb cruise waarbij lezingen en educatie worden gecombineerd met een cruisevakantie.",
    doelgroep: "Geïnteresseerden",
    inschrijflink: "https://lowcarbcruise.com/",
    prijs: "Zie website",
    afbeelding_url: "",
  },
];
