import type { Professional } from "@/lib/types";

// FICTIEVE VOORBEELDDATA — uitsluitend voor ontwikkeldoeleinden.
// Duidelijk herkenbaar als demo (naam bevat "Voorbeeld" / "Demo").

export const MOCK_PROFESSIONALS: Professional[] = [
  {
    id: "demo-1",
    slug: "dr-anke-voorbeeld",
    naam: "Dr. Anke Voorbeeld",
    profielfoto_url: null,
    beroep: "huisarts",
    big_registratie: "BIG 00000000 (voorbeeld)",
    organisatie: "Huisartsenpraktijk De Linde",
    locatie: "Utrecht",
    provincie: "Utrecht",
    postcode: "3511 AB",
    website: "https://voorbeeldpraktijk.nl",
    email: "info@voorbeeldpraktijk.nl",
    telefoonnummer: "030-1234567",
    specialisaties: ["Insulineresistentie", "Diabetes type 2"],
    ervaring_low_carb: true,
    ervaring_diabetes_type_2: true,
    ervaring_obesitas: true,
    ervaring_metabole_gezondheid: true,
    online_consult: true,
    bio: "Begeleidt sinds 2018 patiënten met diabetes type 2 en insulineresistentie bij koolhydraatbeperking, in nauwe samenwerking met diëtisten.",
    goedkeuringsstatus: "approved",
    zichtbaar: true,
    aangemeld_op: "2026-02-10",
  },
  {
    id: "demo-2",
    slug: "mark-de-voorbeeld-dietist",
    naam: "Mark de Voorbeeld",
    profielfoto_url: null,
    beroep: "dietist",
    big_registratie: "Kwaliteitsregister Paramedici (voorbeeld)",
    organisatie: "Voedingspraktijk Kern",
    locatie: "Groningen",
    provincie: "Groningen",
    postcode: "9711 AB",
    website: null,
    email: "mark@voedingspraktijkkern.nl",
    telefoonnummer: null,
    specialisaties: ["Obesitas / gewichtsbeheer", "PCOS"],
    ervaring_low_carb: true,
    ervaring_diabetes_type_2: false,
    ervaring_obesitas: true,
    ervaring_metabole_gezondheid: true,
    online_consult: true,
    bio: "Diëtist met focus op laag-koolhydraat voedingspatronen bij PCOS en gewichtsbeheer, individueel en in groepsverband.",
    goedkeuringsstatus: "approved",
    zichtbaar: true,
    aangemeld_op: "2026-03-02",
  },
  {
    id: "demo-3",
    slug: "fysio-voorbeeld-praktijk",
    naam: "Sanne Voorbeeld",
    profielfoto_url: null,
    beroep: "fysiotherapeut",
    big_registratie: "BIG 00000001 (voorbeeld)",
    organisatie: "Fysio & Leefstijl Zuid",
    locatie: "Eindhoven",
    provincie: "Noord-Brabant",
    postcode: "5611 AB",
    website: "https://fysioleefstijlzuid.nl",
    email: "sanne@fysioleefstijlzuid.nl",
    telefoonnummer: "040-7654321",
    specialisaties: ["Obesitas / gewichtsbeheer", "Hart- en vaatziekten"],
    ervaring_low_carb: true,
    ervaring_diabetes_type_2: true,
    ervaring_obesitas: true,
    ervaring_metabole_gezondheid: false,
    online_consult: false,
    bio: "Combineert beweegprogramma's met leefstijladvies voor mensen met metabole klachten en overgewicht.",
    goedkeuringsstatus: "approved",
    zichtbaar: true,
    aangemeld_op: "2026-01-20",
  },
];
